src/Entity/AvatarUser.php
<?php

namespace App\Entity;

use App\Repository\AvatarUserRepository;
use Doctrine\ORM\Mapping as ORM;

use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\Groups;
use App\Entity\Traits\TimestampableTrait;
use App\Component\File as FileComponent;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=AvatarUserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @Serializer\ExclusionPolicy("ALL")
 */
class AvatarUser extends FileComponent
{
    use TimestampableTrait;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="avatar")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $owner;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Expose
     */
    protected $path;

    public function __construct(File $file)
    {
        $this->file = $file;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl()
    {
        return $_ENV["AWS_BUCKET_URL"] . $this->getPath();
    }

    public function __toString()
    {
        return $this->getUrl();
    }
}

src/Entity/EventDate.php
<?php

namespace App\Entity;

use App\Repository\EventDateRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\Groups;
use App\Entity\Traits\TimestampableTrait;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Persistence\ObjectManagerAware;

/**
 * @ORM\Entity(repositoryClass=EventDateRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @Serializer\ExclusionPolicy("ALL")
 */
class EventDate implements ObjectManagerAware
{
    private $em;
    use TimestampableTrait;
    public function injectObjectManager(
        ObjectManager $objectManager,
        \Doctrine\Persistence\Mapping\ClassMetadata $classMetadata
    ) {
        $this->em = $objectManager;
    }
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Serializer\Expose
     * @Groups({"feedEvent", "new_order"})
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Serializer\Expose
     * @Groups({"feedEvent", "new_order"})
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     * @Serializer\Expose
     * @Groups({"feedEvent", "new_order"})
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity=Position::class, inversedBy="eventDates")
     * @ORM\JoinColumn(nullable=false)
     * @Serializer\Exclude
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Expose
     * @Groups({"feedEvent"})
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Expose
     * @Groups({"feedEvent"})
     */
    private $longitude;
    /**
     * @ORM\Column(type="text")
     * @Serializer\Expose
     * @Groups({"feedEvent", "new_order"})
     */
    private $address;

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("city")
     * @Groups({"feedEvent"})
     * @return string
     */
    public function getCity()
    {
        if(!empty($this->getPosition())) {
            $locale = $GLOBALS['request'] ? $GLOBALS['request']->getLocale() : "ar";
            switch ($locale) {
                case "en":
                    return $this->getPosition()->getCityNameEn();
                    break;
                case "ar":
                    return $this->getPosition()->getCityNameAr();
                    break;
                default:
                    return $this->getPosition()->getCityNameFr();
                    break;
            }
        }
        return null;
    }

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("country")
     * @Groups({"feedEvent"})
     * @return string
     */
    public function getCountry()
    {
        if(!empty($this->getPosition())) {
            $locale = $GLOBALS['request'] ? $GLOBALS['request']->getLocale() : "ar";
            switch ($locale) {
                case "en":
                    return $this->getPosition()->getCountryNameEn();
                    break;
                case "ar":
                    return $this->getPosition()->getCountryNameAr();
                    break;
                default:
                    return $this->getPosition()->getCountryNameFr();
                    break;
            }
        }
        return null;
    }

    /**
     * @ORM\ManyToOne(targetEntity=Event::class, inversedBy="eventDates")
     * @ORM\JoinColumn(nullable=false)
     * @Serializer\Exclude
     */
    private $event;

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("event_name")
     * @Groups({"new_order"})
     * @return string
     */
    public function getEventName()
    {
        return $this->getEvent() ? $this->getEvent()->getName() : null;
    }

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("event_description")
     * @Groups({"new_order"})
     * @return string
     */
    public function getEventDescription()
    {
        return $this->getEvent() ? $this->getEvent()->getDescription() : null;
    }

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("event_cover")
     * @Groups({"new_order"})
     * @return string
     */
    public function getEventCover()
    {
        return $this->getEvent() ? $this->getEvent()->getCoverUrl() : null;
    }

    /**
     * @ORM\OneToMany(targetEntity=Ticket::class, mappedBy="eventDate")
     * @Serializer\Expose
     * @Groups({"feedEvent"})
     */
    private $tickets;

    /**
     * @ORM\OneToOne(targetEntity=WithdrawalRequest::class, mappedBy="eventDate", cascade={"persist", "remove"})
     */
    private $withdrawalRequest;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getPosition(): ?Position
    {
        return $this->position;
    }

    public function setPosition(?Position $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    /**
     * @return Collection|Ticket[]
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets[] = $ticket;
            $ticket->setEventDate($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getEventDate() === $this) {
                $ticket->setEventDate(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getEventName()." [".$this->getStartDate()->format('Y-m-d H:i p')."]"." #".$this->getId();
    }
    public function getWithdrawalRequest(): ?WithdrawalRequest
    {
        return $this->withdrawalRequest;
    }

    public function setWithdrawalRequest(WithdrawalRequest $withdrawalRequest): self
    {
        // set the owning side of the relation if necessary
        if ($withdrawalRequest->getEventDate() !== $this) {
            $withdrawalRequest->setEventDate($this);
        }

        $this->withdrawalRequest = $withdrawalRequest;

        return $this;
    }

    public function getTotalPaidSales()
    {
        return $this->em->getRepository(Torder::class)->getTotalPaidSalesByEventDate($this)?? "0";
    }
    public function getTotalBenefit()
    {
        return (float)$this->getEvent()->getEvtickPercentage() * (float)$this->getTotalPaidSales();
    }
    public function getTotalReceivedByOwner()
    {
        return $this->getTotalPaidSales() - $this->getTotalBenefit();
    }
}

src/Entity/Torder.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Groups;
use App\Entity\Traits\TimestampableTrait;
use JMS\Serializer\Annotation as Serializer;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @Serializer\ExclusionPolicy("ALL")
 */
class Torder
{
    use TimestampableTrait;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $state;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $items_total;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $currency_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customer_ip;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="torder")
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $orderItems;

    /**
     * @ORM\ManyToOne(targetEntity=Beneficiary::class, inversedBy="torder")
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $beneficiary;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     * @Serializer\Expose
     * @Groups({"new_order"})
     */
    private $rated;

    /**
     * @ORM\OneToOne(targetEntity=Tpayment::class, mappedBy="torder", cascade={"persist", "remove"})
     */
    private $tpayment;

    public function __construct()
    {
        $this->rated = false;
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getItemsTotal(): ?string
    {
        return $this->items_total;
    }

    public function setItemsTotal(string $items_total): self
    {
        $this->items_total = $items_total;

        return $this;
    }

    public function getCurrencyCode(): ?string
    {
        return $this->currency_code;
    }

    public function setCurrencyCode(string $currency_code): self
    {
        $this->currency_code = $currency_code;

        return $this;
    }

    public function getCustomerIp(): ?string
    {
        return $this->customer_ip;
    }

    public function setCustomerIp(string $customer_ip): self
    {
        $this->customer_ip = $customer_ip;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems[] = $orderItem;
            $orderItem->setTorder($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getTorder() === $this) {
                $orderItem->setTorder(null);
            }
        }

        return $this;
    }

    public function getBeneficiary(): ?Beneficiary
    {
        return $this->beneficiary;
    }

    public function setBeneficiary(?Beneficiary $beneficiary): self
    {
        $this->beneficiary = $beneficiary;

        return $this;
    }

    public function getRated(): ?bool
    {
        return $this->rated;
    }

    public function setRated(?bool $rated): self
    {
        $this->rated = $rated;

        return $this;
    }

    public function getTpayment(): ?Tpayment
    {
        return $this->tpayment;
    }

    public function setTpayment(?Tpayment $tpayment): self
    {
        // unset the owning side of the relation if necessary
        if ($tpayment === null && $this->tpayment !== null) {
            $this->tpayment->setTorder(null);
        }

        // set the owning side of the relation if necessary
        if ($tpayment !== null && $tpayment->getTorder() !== $this) {
            $tpayment->setTorder($this);
        }

        $this->tpayment = $tpayment;

        return $this;
    }
    public function getFirstEvent()
    {
        return $this->getOrderItems()[0]->getTicket()->getEventDate()->getEvent()->getName();
    }

    public function __toString()
    {
        return $this->getNumber();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/cover.html.twig
{# @var ea \EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext #}
{# @var field \EasyCorp\Bundle\EasyAdminBundle\Dto\FieldDto #}
{# @var entity \EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto #}

{% if field.value is not empty %}
    {% set html_id = 'ea-lightbox-' ~ field.uniqueId %}
    <div class="delete-image-container">
        <a href="#" class="ea-lightbox-thumbnail" data-featherlight="#{{ html_id }}" data-featherlight-close-on-click="anywhere">
            <img style="width: 250px; height: 250px;" src="{{ asset(field.value.url) }}" class="img-fluid">
        </a>

        <div id="{{ html_id }}" class="ea-lightbox">
            <img src="{{ asset(field.value.url) }}">
        </div>
    </div>
{% else %}
    <span> No Cover</span>
{% endif %}

templates/dashboard.html.twig
{#
{% extends '@EasyAdmin/page/content.html.twig' %}
#}

{% extends '@EasyAdmin/layout.html.twig' %}
{% set _content_title = 'Admin dashboard' %}
{#{% block page_title -%}
    {{ _content_title }}
{%- endblock %}
{% block content_header %}
    <h1 class="title">{{ _content_title }}</h1>
{% endblock %}#}

{%
    set url_event = ea_url()
    .setController('App\\Controller\\Admin\\EventCrudController')
    .setAction('index')
%}
{%
    set url_order = ea_url()
    .setController('App\\Controller\\Admin\\TorderCrudController')
    .setAction('index')
%}
{%
    set url_review = ea_url()
    .setController('App\\Controller\\Admin\\TicketRatingCrudController')
    .setAction('index')
%}
{%
    set url_customer = ea_url()
    .setController('App\\Controller\\Admin\\UserCrudController')
    .setAction('index')

%}
{% block main %}

    <div class="row">

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                TOTAL SALES
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"> {{ totalSales ~ " "~currencyCode }}</div>
                            <div class="h8 mb-0 font-weight-bold text-gray-400" style="font-size: x-small;"> -{{ totalSalesPlatformFees~currencyCode~ " Platform fees" }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                PAID ORDERS
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ countPaidOrder }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-cart-arrow-down fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                CUSTOMERS
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ countCustomers }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                AVERAGE ORDER VALUE
                            </div>
                            {% set avgSale = (totalSales and countPaidOrder ? (totalSales/countPaidOrder) : 0) %}
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ (avgSale | number_format(2, '.', ',')) ~ " "~currencyCode }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="far fa-credit-card fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-success">Sales summary</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area data-area-chart" data-sales-numbers="{{ graphSales.sales|json_encode|e('html_attr') }}" data-sales2022-numbers="{{ graphSales2022.sales|json_encode|e('html_attr') }}">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

    </div>



    <!-- Color System -->
    <div class="row">
        <div class="col-lg-3 mb-4">
            <div class="card bg-light text-black shadow">
                <a class="btn btn-lg bg-light rounded" href="{{ url_event }}">
                <div class="card-body">
                    <i class="fas fa-calendar-check"></i> Events
                </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 mb-4">
            <div class="card bg-light text-black shadow">
                <a class="btn btn-lg bg-light rounded" href="{{ url_order }}">
                   <div class="card-body">
                       <i class="fas fa-shopping-cart"></i> Orders
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 mb-4">
            <div class="card bg-light text-black shadow">
                <a class="btn btn-lg bg-light rounded" href="{{ url_customer }}">
                    <div class="card-body">
                        <i class="fas fa-users"></i> Customers
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 mb-4">
            <div class="card bg-light text-black shadow">
                <a class="btn btn-lg bg-light rounded" href="{{ url_review }}">
                   <div class="card-body">
                       <i class="fas fa-newspaper"></i> Reviews
                   </div>
                </a>
            </div>
        </div>

    </div>

    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-6 col-lg-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-success">New customers</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">

                    <div class="table-responsive">
                        <table class="table" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for key, obj in latestCustomers %}
                                {% set url_show = ea_url()
                                    .setController('App\\Controller\\Admin\\UserCrudController')
                                    .setAction('detail')
                                    .setEntityId(obj.id)
                                %}
                                <tr>
                                    <td>{{ obj.fullname }}
                                        <div class="small text-gray-600">{{ obj.email }}</div>
                                    </td>
                                    <td></td>
                                    <td class="text-right"><a class="btn btn-lg bg-light text-black rounded" href="{{ url_show }}"><i class="fas fa-search"></i> show</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
        <!-- Pie Chart -->
        <div class="col-xl-6 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-success"> New orders</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">

                    <div class="table-responsive">
                        <table class="table" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Order</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for key, obj in latestOrders %}
                                {% set url_show = ea_url()
                                    .setController('App\\Controller\\Admin\\TorderCrudController')
                                    .setAction('detail')
                                    .setEntityId(obj.id)
                                %}
                                <tr>
                                    <td>{{ obj.user.fullname }}
                                        <div class="small text-gray-600">{{ obj.user.email }}</div>
                                    </td>
                                    <td>{{ obj.itemsTotal ~ " "~currencyCode }}</td>
                                    <td class="text-right"><a class="btn btn-lg bg-light text-black rounded" href="{{ url_show }}"><i class="fas fa-search"></i> show</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>


    </div>




{% endblock %}

templates/items.html.twig
{# @var ea \EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext #}
{# @var field \EasyCorp\Bundle\EasyAdminBundle\Dto\FieldDto #}
{# @var entity \EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto #}


{% set html_id = 'ea-lightbox-' ~ field.uniqueId %}
<div><ul>
          <li>
               <p> {{ field.value[0].quantity }} Ticket(s) {{ field.value[0].ticket.type }}</p>
               <p> {{ field.value[0].ticket.eventDate.event.name }} at {{ field.value[0].ticket.eventDate.startDate | date('Y-m-d H:i:sP') }} </p>
               <p> {{ field.value[0].ticket.eventDate.address }}. </p>
          </li>
     </ul>
{#
     <p> {{ field.value[0].total }}</p>
     <p> {{ field.value[0].ticket.id }}</p>
     <p> {{ field.value[0].ticket.type }}</p>
     <p> {{ field.value[0].ticket.price }}</p>
     <p> {{ field.value[0].ticket.eventDate.startDate | date('Y-m-d H:i:s') }}</p>
     <p> {{ field.value[0].ticket.eventDate.endDate | date('Y-m-d H:i:s') }}</p>
     <p> {{ field.value[0].ticket.eventDate.address }}</p>
    <p> {{ field.value[0].ticket.eventDate.event.name }}</p>
#}

</div>

templates/state.html.twig
{% if field.value is not empty %}

{% if field.value == "new" %}
        <span  class="btn btn-sm btn-info custom-button rounded">
            <i class="fas fa-inbox text-left"></i>    new
        </span>
{% elseif field.value == "request_payment" %}
        <span  class="btn btn-sm btn-warning custom-button rounded">
            <i class="fas fa-clock text-left"></i>    awaiting payment
        </span>
{% elseif field.value == "payment_nok" %}
        <span  class="btn btn-sm btn-danger custom-button rounded">
            <i class="fas fa-window-close text-left"></i>    failed
        </span>
{% elseif field.value == "request_payment_confirm" %}
        <span  class="btn btn-sm btn-warning custom-button rounded">
            <i class="fas fa-clock text-left"></i>    awaiting payment
        </span>
{% elseif field.value == "payment_ok" %}
       <span class="btn btn-sm btn-success custom-button rounded">
            <i class="fas fa-check text-left"></i>    paid
        </span>
{% else %}
    <span> No Value </span>
{% endif %}

{% else %}
    <span> No Value </span>
{% endif %}

templates/state_withdraw.html.twig
{% if field.value is not empty %}

    {% if field.value == "requested" %}
        <span  class="btn btn-sm btn-warning custom-button rounded">
            <i class="fas fa-clock text-left"></i>    awaiting review
        </span>
    {% elseif field.value == "confirmed" %}
        <span class="btn btn-sm btn-success custom-button rounded">
            <i class="fas fa-check text-left"></i>    confirmed
        </span>
    {% else %}
        <span> No Value </span>
    {% endif %}

{% else %}
    <span> No Value </span>
{% endif %}